# TRACE|DEBUG|INFO|WARN|ERROR
logging:
  level:
    root: WARN
  file: rason.log
spring: 
  application: 
    name: rason	
  main: 
    banner-mode: "off"
  pid:
    fail-on-write-error: true
    file: ${spring.application.name}.pid
server:
  port: ${port:9090}
rason: 
  slugMaxLength: 50
  slugGenMaxRetry: 10
  maxBuckets: 50
  maxCacheSize: 2000
  maxSessionLifeMinutes: 600
  maxCacheLifeMinutes: 14400
